### ISSUE TITLE
Problem with Fourq?

### ISSUE THREAD

**Issue by billbuchanan** [cloudflare/circl#94] opened 2020-03-08 21:52 UTC
I can get most of the Circl code to work, but Fourq gives an exception. With just a simple example, it crashes when using P.ScalarBaseMult():

package main

import (
	"crypto/rand"
	"fmt"
	"io"

	"github.com/cloudflare/circl/ecc/fourq"
)

// Size is the size in bytes of keys.
const Size = 32

// Key represents a public or private key of FourQ.
type Key [Size]byte

// KeyGen calculates a public key k from a secret key.
func KeyGen(public, secret *Key) {

	var P fourq.Point

	P.ScalarBaseMult((*[32]byte)(secret))

	P.Marshal((*[Size]byte)(public))
}

// Shared calculates a shared key k from Alice's secret and Bob's public key.
// Returns true on success.
func Shared(shared, secret, public *Key) bool {
	var P, Q fourq.Point

	ok := P.Unmarshal((*[Size]byte)(public))

	Q.ScalarMult((*[Size]byte)(secret), &P)
	Q.Marshal((*[Size]byte)(shared))
	ok = ok && Q.IsOnCurve()
	return ok
}
func main() {

	var AliceSecret, BobSecret,
		AlicePublic, BobPublic,
		AliceShared, BobShared Key

	// Generating Alice's secret and public keys
	_, _ = io.ReadFull(rand.Reader, AliceSecret[:32])

	fmt.Println("Secret ", AliceSecret)
	KeyGen(&AlicePublic, &AliceSecret)

	fmt.Println("Key %x", AliceSecret)
	// Generating Bob's secret and public keys
	_, _ = io.ReadFull(rand.Reader, BobSecret[:])
	KeyGen(&BobPublic, &BobSecret)

	// Deriving Alice's shared key
	Shared(&AliceShared, &AliceSecret, &BobPublic)

	// Deriving Bob's shared key
	Shared(&BobShared, &BobSecret, &AlicePublic)

	fmt.Println(AliceShared == BobShared)

}

C:\> fourq.exe
Secret  [248 49 197 200 23 204 9 133 172 96 220 181 247 45 113 172 201 21 31 235
 30 186 124 42 183 115 114 250 127 187 194 224]
Exception 0xc000001d 0x0 0x0 0x4b2758
PC=0x4b2758

github.com/cloudflare/circl/ecc/fourq.doubleAsm(0xc00007bd10)
        d:/go/src/src/github.com/cloudflare/circl/ecc/fourq/point_amd64.s:8 +0x8
8
github.com/cloudflare/circl/ecc/fourq.(*pointR1).double(...)
        d:/go/src/src/github.com/cloudflare/circl/ecc/fourq/point_amd64.go:24
github.com/cloudflare/circl/ecc/fourq.(*pointR1).ScalarBaseMult(0xc00007bd10, 0x
c00004e140)
        d:/go/src/src/github.com/cloudflare/circl/ecc/fourq/point.go:190 +0x284
github.com/cloudflare/circl/ecc/fourq.(*Point).ScalarBaseMult(0xc00007bdd0, 0xc0
0004e140)
        d:/go/src/src/github.com/cloudflare/circl/ecc/fourq/curve.go:82 +0x70
main.KeyGen(0xc00007bec8, 0xc00004e140)
        C:/Python27/godir/fourq.go:22 +0x53
main.main()
        C:/Python27/godir/fourq.go:49 +0x1d0
rax     0x0
rbx     0x0
rcx     0x0
rdi     0xc00007bd10
rsi     0x0
rbp     0xc00007bcf0
rsp     0xc00007bb28
r8      0x0
r9      0x0
r10     0x0
r11     0x0
r12     0x7c2526
r13     0x4db6e0
r14     0x0
r15     0x0
rip     0x4b2758
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by armfazh** [comment] 2020-03-09 20:09
@billbuchanan we will investigate this issue. In the meantime, which Go version did you use? Did you see this error with other keys, or it is a consistent error for any key?

**Comment by billbuchanan** [comment] 2020-03-09 20:17
I am using Go 1.12.6 windows/amd64

I have managed to get all of the other key exchange methods to work (post-quantum, X25519,  X488, and so on), but I get an exception with Fourq. My CPU is AMD Phenom II X6 1055T, 2.80 GHz.

**Comment by henrydcase** [comment] 2020-03-10 16:19
As far as I remember FourQ uses ``MULXQ`` instruction which may not be supported on your CPU. 

https://github.com/cloudflare/circl/blob/79a11e7682ca5490bbcfa076ac102076d43996a4/ecc/fourq/fq_amd64.h#L129

The fix which worked for me was to first check if CPU supports MULX and, if not, fallback to unoptimized implementation which doesn't use assembly (I think I needed to add non-assembly implementation to my local clone). 

Obviously using newer CPU "solves" the issue :)

**Comment by billbuchanan** [comment] 2020-03-10 16:56
Thanks for this. Do you have instructions on building for the non-assembly implementation?

**Comment by armfazh** [comment] 2020-03-10 20:32
I am working on a patch, it will be released this week.

**Comment by billbuchanan** [comment] 2020-03-10 20:56
Thank you so much. Excellent support, and love the library.

**Comment by armfazh** [comment] 2020-03-25 23:05
The PR #96 has added support for legacy multiplication instructions. 
Let us know if some other issues arise.

**Closed by armfazh** 2020-03-25 23:05 UTC
Labels: needs investigation

**Comment by billbuchanan** [comment] 2020-03-31 19:47
Thanks for the update. I now get the error of:
\github.com\cloudflare\circl\ecc\fourq\fp_amd64.s:50: unrecognized instruction "_fpMulLeg"
asm: assembly of github.com\cloudflare\circl\ecc\fourq\fp_amd64.s failed

**Comment by armfazh** [comment] 2020-03-31 21:37
@billbuchanan 
I could not reproduce that failure. I tried using go1.12.6, but in a linux machine.
Does that error happen during compilation or running time?

I recommend you to update Go to a more recent version. Also, make sure to clean compilation cache using `go clean -cache`

**Comment by billbuchanan** [comment] 2020-04-01 06:44
I have:

go version go1.12.6 windows/amd64

and have cleaned the cache. The error happens on compilation, and fails to find "_fpMulLeg"

**Comment by billbuchanan** [comment] 2020-04-01 07:00
I can get it to compile now, but I get a runtime error:
c:>fourq.exe
Secret  [250 133 245 228 228 163 21 170 121 63 215 199 226 215 181 104 55 156 72
 117 141 179 146 105 216 0 226 124 140 33 131 80]

Exception 0xc000001d 0x0 0x0 0x4b2758
PC=0x4b2758

github.com/cloudflare/circl/ecc/fourq.doubleAsm(0xc000085d10)
        d:/go/src/src/github.com/cloudflare/circl/ecc/fourq/point_amd64.s:8 +0x8
8
github.com/cloudflare/circl/ecc/fourq.(*pointR1).double(...)
        d:/go/src/src/github.com/cloudflare/circl/ecc/fourq/point_amd64.go:24
github.com/cloudflare/circl/ecc/fourq.(*pointR1).ScalarBaseMult(0xc000085d10, 0x
c000058140)
        d:/go/src/src/github.com/cloudflare/circl/ecc/fourq/point.go:190 +0x284
github.com/cloudflare/circl/ecc/fourq.(*Point).ScalarBaseMult(0xc000085dd0, 0xc0
00058140)
        d:/go/src/src/github.com/cloudflare/circl/ecc/fourq/curve.go:82 +0x70
main.KeyGen(0xc000085ec8, 0xc000058140)
        c:/Python27/godir/fourq.go:22 +0x53
main.main()
        c:/Python27/godir/fourq.go:49 +0x1d0
rax     0x0
rbx     0x0
rcx     0x0
rdi     0xc000085d10
rsi     0x0
rbp     0xc000085cf0
rsp     0xc000085b28
r8      0x0
r9      0x0
r10     0x0
r11     0x0
r12     0x6c2a26
r13     0x4db6e0
r14     0x0
r15     0x0
rip     0x4b2758
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by billbuchanan** [comment] 2020-04-01 07:18
I even took it right back to:

var P fourq.Point


var k [32]byte

_, _ = rand.Read(k[:])

P.ScalarBaseMult(&k)

and still generated the exception.

**Comment by armfazh** [comment] 2020-04-01 09:25
Please take a look on your go.mod file, it should point to the `master` version rather than to v1.0.0.

File: go.mod
```go
module main

go 1.13

require github.com/cloudflare/circl master
```

Note that the error message still points to the function `doubleAsm`, which was removed after you reported us the initial bug.

> github.com/cloudflare/circl/ecc/fourq.doubleAsm(0xc000085d10)
> d:/go/src/src/github.com/cloudflare/circl/ecc/fourq/point_amd64.s:8 +0x8

**Comment by billbuchanan** [comment] 2020-04-01 18:58
You are correct. It was using the old version of the code. I had to remove the old version of the Circl library, and fully re-download. It works perfectly now:

[Online demo](https://asecuritysite.com/encryption/go_fourq)
